import {useState,useRef,useEffect} from 'react';
import {Mic,Square,Volume2,RotateCcw} from 'lucide-react';
function wav(chunks:Float32Array[],rate:number){const n=chunks.reduce((s,a)=>s+a.length,0),buf=new ArrayBuffer(44+n*2),v=new DataView(buf);const str=(p:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(p+i,s.charCodeAt(i))};str(0,'RIFF');v.setUint32(4,36+n*2,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,n*2,true);let o=44;for(const chunk of chunks)for(const x of chunk){v.setInt16(o,Math.max(-1,Math.min(1,x))*32767,true);o+=2}const b=new Uint8Array(buf);let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s)}

export default function Voice({language,onTranscript,onAnswer,history}:{language:string,onTranscript:(s:string)=>void,onAnswer:(x:any)=>void,history:any[]}){
 const [state,setState]=useState('idle'),[error,setError]=useState(''),[level,setLevel]=useState(0),[profile,setProfile]=useState(localStorage.getItem('dharohar-voice-profile')||'warm'),[notice,setNotice]=useState('Neural narration · synthetic voice');
 const stream=useRef<MediaStream|null>(null),ctx=useRef<AudioContext|null>(null),playback=useRef<AudioContext|null>(null),socket=useRef<WebSocket|null>(null),player=useRef<AudioBufferSourceNode|null>(null),chunks=useRef<Float32Array[]>([]),lastSpeech=useRef(0),started=useRef(0),mode=useRef('idle'),previous=useRef<{audio:string,mime:string}|null>(null),h=useRef(history),lang=useRef(language),profileRef=useRef(profile),generation=useRef(0),requestId=useRef(0),playbackId=useRef(0);
 h.current=history;lang.current=language;profileRef.current=profile;
 useEffect(()=>{localStorage.setItem('dharohar-voice-profile',profile)},[profile]);
 function change(s:string){mode.current=s;setState(s)}
 function stopAudio(){playbackId.current++;if(player.current){player.current.onended=null;player.current.stop();player.current=null}}
 function stop(){generation.current++;requestId.current++;const ws=socket.current;socket.current=null;if(ws){ws.onclose=null;ws.onmessage=null;ws.onerror=null;if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'cancel'}));ws.close()}stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(ctx.current&&ctx.current.state!=='closed')void ctx.current.close();ctx.current=null;stopAudio();if(playback.current&&playback.current.state!=='closed')void playback.current.close();playback.current=null;chunks.current=[];started.current=0;lastSpeech.current=0;change('idle');setLevel(0)}
 useEffect(()=>()=>stop(),[]);
 async function play(event:{audio:string,mime:string}){stopAudio();const token=generation.current,id=playbackId.current;change('speaking');try{if(!playback.current||playback.current.state==='closed')playback.current=new AudioContext();const audioContext=playback.current;await audioContext.resume();const bytes=Uint8Array.from(atob(event.audio),c=>c.charCodeAt(0)),buffer=await audioContext.decodeAudioData(bytes.buffer);if(token!==generation.current||id!==playbackId.current)return;const node=audioContext.createBufferSource();node.buffer=buffer;node.connect(audioContext.destination);player.current=node;node.onended=()=>{if(token!==generation.current||id!==playbackId.current)return;player.current=null;chunks.current=[];started.current=0;lastSpeech.current=0;change(socket.current?'listening':'idle')};node.start()}catch{if(token!==generation.current)return;setError('Audio could not start. Use Repeat, or read the response below.');change(socket.current?'ready':'idle')}}
 function interrupt(){if(socket.current?.readyState!==WebSocket.OPEN)return;requestId.current++;socket.current.send(JSON.stringify({type:'cancel'}));stopAudio();chunks.current=[];started.current=0;lastSpeech.current=0;change('listening')}
 async function start(){if(mode.current!=='idle')return;const token=++generation.current;setError('');change('connecting');try{
  playback.current=new AudioContext();await playback.current.resume();
  const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(token!==generation.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;
  const audio=new AudioContext({sampleRate:16000});ctx.current=audio;const source=audio.createMediaStreamSource(media),processor=audio.createScriptProcessor(2048,1,1);source.connect(processor);processor.connect(audio.destination);
  const ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/api/voice/live');socket.current=ws;
  ws.onmessage=e=>{if(token!==generation.current||socket.current!==ws)return;const event=JSON.parse(e.data);if(event.request_id!==undefined&&event.request_id!==requestId.current)return;
   if(event.type==='ready'){setNotice(event.notice||'Neural narration · synthetic voice');if(event.languages&&!event.languages.includes(lang.current)){setError('This language needs the online voice provider. Local voices cover English and Hindi.');stop();return}if(!event.stt||!event.tts){setError('Speech services are unavailable. Please check the selected provider.');stop();return}change('listening')}
   if(event.type==='state')change(event.state==='ready'?'listening':event.state);if(event.type==='transcript')onTranscript(event.text);if(event.type==='answer')onAnswer(event);if(event.type==='audio'){previous.current=event;void play(event)}if(event.type==='error'){setError(event.message);change('listening')}
  };
  ws.onerror=()=>{if(token!==generation.current)return;setError('The voice service could not be reached.');stop()};ws.onclose=()=>{if(token===generation.current&&mode.current!=='idle'){setError('Voice connection closed. Start again to reconnect.');stop()}};
  processor.onaudioprocess=e=>{if(token!==generation.current||mode.current!=='listening'||ws.readyState!==WebSocket.OPEN)return;const samples=e.inputBuffer.getChannelData(0),rms=Math.sqrt(samples.reduce((s,x)=>s+x*x,0)/samples.length);setLevel(Math.min(1,rms*10));const now=Date.now();if(rms>.017){lastSpeech.current=now;if(!started.current)started.current=now}if(started.current)chunks.current.push(new Float32Array(samples));if(started.current&&((now-lastSpeech.current>650&&now-started.current>650)||now-started.current>25000)){const payload=wav(chunks.current,audio.sampleRate);chunks.current=[];started.current=0;setLevel(0);change('transcribing');ws.send(JSON.stringify({type:'audio',request_id:++requestId.current,audio:payload,language:lang.current,profile:profileRef.current,history:h.current.slice(-6).map(x=>({role:x.role,content:x.content}))}))}};
 }catch(e:any){if(token!==generation.current)return;setError(e.name==='NotAllowedError'?'Microphone access was not granted. Allow it in your browser to start a conversation.':e.message);stop()}}
 const labels:any={idle:'A conversation starts with your voice.',connecting:'Connecting to your assistant…',listening:'I’m listening. Speak naturally.',transcribing:'Listening back to your question…',thinking:'Let’s explore that…',speaking:'Speaking. Your sources appear below.',ready:'Ready to continue.'};
 return <section className="voice-stage"><div className={'voice-orb '+(state==='speaking'?'pulse':'')} style={{transform:`scale(${1+level*.18})`}}><Mic size={38}/></div><h2>{labels[state]||state}</h2><p>Say hello or ask a question. We can explore the ideas together.</p><label className="voice-preference">Narrator <select aria-label="Voice style" value={profile} disabled={state!=='idle'} onChange={e=>setProfile(e.target.value)}><option value="warm">Warm & welcoming</option><option value="clear">Clear & conversational</option><option value="strong">Resonant & composed</option></select></label><div className="actions">{state==='idle'?<button className="button primary" onClick={()=>void start()}><Mic size={18}/>Start conversation</button>:<><button className="button secondary" disabled={state==='connecting'} onClick={interrupt}><Mic size={17}/>Interrupt & speak</button><button className="button secondary" onClick={stop}><Square size={16}/>End</button></>}{previous.current&&<button className="icon-button" aria-label="Repeat last answer" onClick={()=>void play(previous.current!)}><RotateCcw size={20}/></button>}</div><div className="voice-caption"><Volume2 size={14}/>{notice}</div>{error&&<p className="error" role="alert">{error}</p>}</section>
}
